export const SUPPLIER_FORM_CHANGE = 'SUPPLIER_FORM_CHANGE';
export const SUPPLIER_FORM_VALIDATION = 'SUPPLIER_FORM_VALIDATION';
export const SUPPLIER_FORM_CLEAR = 'SUPPLIER_FORM_CLEAR';
export const SUPPLIER_FORM_CHANGE_MODE = 'SUPPLIER_FORM_CHANGE_MODE';

export const SUPPLIER_CHANGE_LIST = 'SUPPLIER_CHANGE_LIST';
export const SUPPLIER_PUSH_LIST = 'SUPPLIER_PUSH_LIST';
export const SUPPLIER_REMOVE_LIST = 'SUPPLIER_REMOVE_LIST';
export const SUPPLIER_UPDATE_LIST = 'SUPPLIER_UPDATE_LIST';
export const SUPPLIER_CHANGE_SEARCH_LIST = 'SUPPLIER_CHANGE_SEARCH_LIST';
export const SUPPLIER_FILTER_LIST = 'SUPPLIER_FILTER_LIST';

export const SUPPLIER_CHANGE_DETAIL = 'SUPPLIER_CHANGE_DETAIL';