//TẢI LIST INTERNAL STOCK DELIVERY
export const INTERNAL_STOCK_DELIVERY_CHANGE_LIST = 'INTERNAL_STOCK_DELIVERY_CHANGE_LIST';
export const INTERNAL_STOCK_DELIVERY_CHANGE_LIST_CHILD = 'INTERNAL_STOCK_DELIVERY_CHANGE_LIST_CHILD';
export const INTERNAL_STOCK_DELIVERY_CLEAR_LIST_CHILD = 'INTERNAL_STOCK_DELIVERY_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const INTERNAL_STOCK_DELIVERY_PUSH_LIST_CHILD = 'INTERNAL_STOCK_DELIVERY_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const INTERNAL_STOCK_DELIVERY_CHANGE_SELECTED_DETAIL = 'INTERNAL_STOCK_DELIVERY_CHANGE_SELECTED_DETAIL';
export const INTERNAL_STOCK_DELIVERY_CLEAR_SELECTED_DETAIL = 'INTERNAL_STOCK_DELIVERY_CLEAR_SELECTED_DETAIL';
export const INTERNAL_STOCK_DELIVERY_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'INTERNAL_STOCK_DELIVERY_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const INTERNAL_STOCK_DELIVERY_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'INTERNAL_STOCK_DELIVERY_CLEAR_LIST_CHILD_SELECTED_DETAIL';

export const INTERNAL_STOCK_DELIVERY_FORM_CHANGE = 'INTERNAL_STOCK_DELIVERY_FORM_CHANGE';
export const INTERNAL_STOCK_DELIVERY_FORM_VALIDATION = 'INTERNAL_STOCK_DELIVERY_FORM_VALIDATION';
export const INTERNAL_STOCK_DELIVERY_FORM_CHANGE_VALUES = 'INTERNAL_STOCK_DELIVERY_FORM_CHANGE_VALUES';
export const INTERNAL_STOCK_DELIVERY_FORM_CLEAR = 'INTERNAL_STOCK_DELIVERY_FORM_CLEAR'; //CLEAR FORM CHA
export const INTERNAL_STOCK_DELIVERY_CHANGE_MODE = 'INTERNAL_STOCK_DELIVERY_CHANGE_MODE';

export const INTERNAL_STOCK_DELIVERY_FORM_CHILD_CHANGE = 'INTERNAL_STOCK_DELIVERY_FORM_CHILD_CHANGE';
export const INTERNAL_STOCK_DELIVERY_FORM_CHILD_CHANGE_MODE = 'INTERNAL_STOCK_DELIVERY_FORM_CHILD_CHANGE_MODE';
export const INTERNAL_STOCK_DELIVERY_FORM_CHILD_CLEAR = 'INTERNAL_STOCK_DELIVERY_FORM_CHILD_CLEAR';
export const INTERNAL_STOCK_DELIVERY_FORM_CHILD_VALIDATION = 'INTERNAL_STOCK_DELIVERY_FORM_CHILD_VALIDATION';
export const INTERNAL_STOCK_DELIVERY_FORM_CHILD_UPDATE_LIST = 'INTERNAL_STOCK_DELIVERY_FORM_CHILD_UPDATE_LIST'; // Update list child