//TẢI LIST INTERNAL STOCK DELIVERY
export const KHACH_LE_TRA_HANG_CHANGE_LIST = 'KHACH_LE_TRA_HANG_CHANGE_LIST';
export const KHACH_LE_TRA_HANG_CHANGE_LIST_CHILD = 'KHACH_LE_TRA_HANG_CHANGE_LIST_CHILD';
export const KHACH_LE_TRA_HANG_CLEAR_LIST_CHILD = 'KHACH_LE_TRA_HANG_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const KHACH_LE_TRA_HANG_PUSH_LIST_CHILD = 'KHACH_LE_TRA_HANG_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const KHACH_LE_TRA_HANG_CHANGE_SELECTED_DETAIL = 'KHACH_LE_TRA_HANG_CHANGE_SELECTED_DETAIL';
export const KHACH_LE_TRA_HANG_CLEAR_SELECTED_DETAIL = 'KHACH_LE_TRA_HANG_CLEAR_SELECTED_DETAIL';
export const KHACH_LE_TRA_HANG_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'KHACH_LE_TRA_HANG_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const KHACH_LE_TRA_HANG_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'KHACH_LE_TRA_HANG_CLEAR_LIST_CHILD_SELECTED_DETAIL';

export const KHACH_LE_TRA_HANG_FORM_CHANGE = 'KHACH_LE_TRA_HANG_FORM_CHANGE';
export const KHACH_LE_TRA_HANG_FORM_VALIDATION = 'KHACH_LE_TRA_HANG_FORM_VALIDATION';
export const KHACH_LE_TRA_HANG_FORM_CHANGE_VALUES = 'KHACH_LE_TRA_HANG_FORM_CHANGE_VALUES';
export const KHACH_LE_TRA_HANG_FORM_CLEAR = 'KHACH_LE_TRA_HANG_FORM_CLEAR'; //CLEAR FORM CHA
export const KHACH_LE_TRA_HANG_CHANGE_MODE = 'KHACH_LE_TRA_HANG_CHANGE_MODE';

export const KHACH_LE_TRA_HANG_FORM_CHILD_CHANGE = 'KHACH_LE_TRA_HANG_FORM_CHILD_CHANGE';
export const KHACH_LE_TRA_HANG_FORM_CHILD_CHANGE_MODE = 'KHACH_LE_TRA_HANG_FORM_CHILD_CHANGE_MODE';
export const KHACH_LE_TRA_HANG_FORM_CHILD_CLEAR = 'KHACH_LE_TRA_HANG_FORM_CHILD_CLEAR';
export const KHACH_LE_TRA_HANG_FORM_CHILD_VALIDATION = 'KHACH_LE_TRA_HANG_FORM_CHILD_VALIDATION';
export const KHACH_LE_TRA_HANG_CHANGE_SEARCH_LIST = 'KHACH_LE_TRA_HANG_CHANGE_SEARCH_LIST';
export const KHACH_LE_TRA_HANG_CHANGE_CHANGE_DISABLED = 'KHACH_LE_TRA_HANG_CHANGE_CHANGE_DISABLED';

// Search list 
export const KHACH_LE_TRA_HANG_CHANGE_SEARCH_RESULT_LIST = 'KHACH_LE_TRA_HANG_CHANGE_SEARCH_RESULT_LIST';
export const KHACH_LE_TRA_HANG_CHANGE_SEARCH_RESULT_SELECTED_DETAIL = 'KHACH_LE_TRA_HANG_CHANGE_SEARCH_RESULT_SELECTED_DETAIL';
// End search list