export const MEDICINE_UPDATE_PRICE_FORM_CHANGE = 'MEDICINE_UPDATE_PRICE_FORM_CHANGE';
export const MEDICINE_UPDATE_PRICE_FORM_VALIDATION = 'MEDICINE_UPDATE_PRICE_FORM_VALIDATION';
export const MEDICINE_UPDATE_PRICE_FORM_CLEAR = 'MEDICINE_UPDATE_PRICE_FORM_CLEAR';
export const MEDICINE_UPDATE_PRICE_FORM_CHANGE_MODE = 'MEDICINE_UPDATE_PRICE_FORM_CHANGE_MODE';

export const MEDICINE_UPDATE_PRICE_CHANGE_LIST = 'MEDICINE_UPDATE_PRICE_CHANGE_LIST';
export const MEDICINE_UPDATE_PRICE_PUSH_LIST = 'MEDICINE_UPDATE_PRICE_PUSH_LIST';
export const MEDICINE_UPDATE_PRICE_REMOVE_LIST = 'MEDICINE_UPDATE_PRICE_REMOVE_LIST';
export const MEDICINE_UPDATE_PRICE_UPDATE_LIST = 'MEDICINE_UPDATE_PRICE_UPDATE_LIST';
export const MEDICINE_UPDATE_PRICE_CHANGE_SEARCH_LIST = 'MEDICINE_UPDATE_PRICE_CHANGE_SEARCH_LIST';
export const MEDICINE_UPDATE_PRICE_CLEAR_SEARCH_LIST = 'MEDICINE_UPDATE_PRICE_CLEAR_SEARCH_LIST';
export const MEDICINE_UPDATE_PRICE_FILTER_LIST = 'MEDICINE_UPDATE_PRICE_FILTER_LIST';

export const MEDICINE_UPDATE_PRICE_CHANGE_DETAIL = 'MEDICINE_UPDATE_PRICE_CHANGE_DETAIL';
export const MEDICINE_UPDATE_PRICE_CHANGE_PRODUCT_INPUT_DETAIL = 'MEDICINE_UPDATE_PRICE_CHANGE_PRODUCT_INPUT_DETAIL';