//TẢI LIST INTERNAL STOCK DELIVERY
export const MEDICINE_EXPIRE_CHANGE_LIST = 'MEDICINE_EXPIRE_CHANGE_LIST';
export const MEDICINE_EXPIRE_CHANGE_LIST_CHILD = 'MEDICINE_EXPIRE_CHANGE_LIST_CHILD';
export const MEDICINE_EXPIRE_CLEAR_LIST_CHILD = 'MEDICINE_EXPIRE_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const MEDICINE_EXPIRE_PUSH_LIST_CHILD = 'MEDICINE_EXPIRE_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const MEDICINE_EXPIRE_CHANGE_SELECTED_DETAIL = 'MEDICINE_EXPIRE_CHANGE_SELECTED_DETAIL';
export const MEDICINE_EXPIRE_CLEAR_SELECTED_DETAIL = 'MEDICINE_EXPIRE_CLEAR_SELECTED_DETAIL';
export const MEDICINE_EXPIRE_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'MEDICINE_EXPIRE_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const MEDICINE_EXPIRE_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'MEDICINE_EXPIRE_CLEAR_LIST_CHILD_SELECTED_DETAIL';

export const MEDICINE_EXPIRE_FORM_CHANGE = 'MEDICINE_EXPIRE_FORM_CHANGE';
export const MEDICINE_EXPIRE_FORM_VALIDATION = 'MEDICINE_EXPIRE_FORM_VALIDATION';
export const MEDICINE_EXPIRE_FORM_CHANGE_VALUES = 'MEDICINE_EXPIRE_FORM_CHANGE_VALUES';
export const MEDICINE_EXPIRE_FORM_CLEAR = 'MEDICINE_EXPIRE_FORM_CLEAR'; //CLEAR FORM CHA
export const MEDICINE_EXPIRE_CHANGE_MODE = 'MEDICINE_EXPIRE_CHANGE_MODE';

export const MEDICINE_EXPIRE_FORM_CHILD_CHANGE = 'MEDICINE_EXPIRE_FORM_CHILD_CHANGE';
export const MEDICINE_EXPIRE_FORM_CHILD_CHANGE_MODE = 'MEDICINE_EXPIRE_FORM_CHILD_CHANGE_MODE';
export const MEDICINE_EXPIRE_FORM_CHILD_CLEAR = 'MEDICINE_EXPIRE_FORM_CHILD_CLEAR';
export const MEDICINE_EXPIRE_FORM_CHILD_VALIDATION = 'MEDICINE_EXPIRE_FORM_CHILD_VALIDATION';