export const MEDICINE_GROUP_FORM_CHANGE = 'MEDICINE_GROUP_FORM_CHANGE';
export const MEDICINE_GROUP_FORM_VALIDATION = 'MEDICINE_GROUP_FORM_VALIDATION';
export const MEDICINE_GROUP_FORM_CLEAR = 'MEDICINE_GROUP_FORM_CLEAR';
export const MEDICINE_GROUP_FORM_CHANGE_MODE = 'MEDICINE_GROUP_FORM_CHANGE_MODE';

export const MEDICINE_GROUP_CHANGE_LIST = 'MEDICINE_GROUP_CHANGE_LIST';
export const MEDICINE_GROUP_PUSH_LIST = 'MEDICINE_GROUP_PUSH_LIST';
export const MEDICINE_GROUP_REMOVE_LIST = 'MEDICINE_GROUP_REMOVE_LIST';
export const MEDICINE_GROUP_UPDATE_LIST = 'MEDICINE_GROUP_UPDATE_LIST';
export const MEDICINE_GROUP_CHANGE_SEARCH_LIST = 'MEDICINE_GROUP_CHANGE_SEARCH_LIST';
export const MEDICINE_GROUP_FILTER_LIST = 'MEDICINE_GROUP_FILTER_LIST';

export const MEDICINE_GROUP_CHANGE_DETAIL = 'MEDICINE_GROUP_CHANGE_DETAIL';