//TẢI LIST INTERNAL STOCK DELIVERY
export const SO_NHAP_THUOC_CHANGE_LIST = 'SO_NHAP_THUOC_CHANGE_LIST';
export const SO_NHAP_THUOC_CHANGE_LIST_CHILD = 'SO_NHAP_THUOC_CHANGE_LIST_CHILD';
export const SO_NHAP_THUOC_CLEAR_LIST_CHILD = 'SO_NHAP_THUOC_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const SO_NHAP_THUOC_PUSH_LIST_CHILD = 'SO_NHAP_THUOC_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const SO_NHAP_THUOC_CHANGE_SELECTED_DETAIL = 'SO_NHAP_THUOC_CHANGE_SELECTED_DETAIL';
export const SO_NHAP_THUOC_CLEAR_SELECTED_DETAIL = 'SO_NHAP_THUOC_CLEAR_SELECTED_DETAIL';
export const SO_NHAP_THUOC_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'SO_NHAP_THUOC_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const SO_NHAP_THUOC_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'SO_NHAP_THUOC_CLEAR_LIST_CHILD_SELECTED_DETAIL';
export const SO_NHAP_THUOC_CHANGE_SEARCH_LIST = 'SO_NHAP_THUOC_CHANGE_SEARCH_LIST';

export const SO_NHAP_THUOC_FORM_CHANGE = 'SO_NHAP_THUOC_FORM_CHANGE';
export const SO_NHAP_THUOC_FORM_VALIDATION = 'SO_NHAP_THUOC_FORM_VALIDATION';
export const SO_NHAP_THUOC_FORM_CHANGE_VALUES = 'SO_NHAP_THUOC_FORM_CHANGE_VALUES';
export const SO_NHAP_THUOC_FORM_CLEAR = 'SO_NHAP_THUOC_FORM_CLEAR'; //CLEAR FORM CHA
export const SO_NHAP_THUOC_CHANGE_MODE = 'SO_NHAP_THUOC_CHANGE_MODE';

export const SO_NHAP_THUOC_FORM_CHILD_CHANGE = 'SO_NHAP_THUOC_FORM_CHILD_CHANGE';
export const SO_NHAP_THUOC_FORM_CHILD_CHANGE_MODE = 'SO_NHAP_THUOC_FORM_CHILD_CHANGE_MODE';
export const SO_NHAP_THUOC_FORM_CHILD_CLEAR = 'SO_NHAP_THUOC_FORM_CHILD_CLEAR';
export const SO_NHAP_THUOC_FORM_CHILD_VALIDATION = 'SO_NHAP_THUOC_FORM_CHILD_VALIDATION';