export const STORAGE_CONDITION_FORM_CHANGE = 'STORAGE_CONDITION_FORM_CHANGE';
export const STORAGE_CONDITION_FORM_VALIDATION = 'STORAGE_CONDITION_FORM_VALIDATION';
export const STORAGE_CONDITION_FORM_CLEAR = 'STORAGE_CONDITION_FORM_CLEAR';
export const STORAGE_CONDITION_FORM_CHANGE_MODE = 'STORAGE_CONDITION_FORM_CHANGE_MODE';

export const STORAGE_CONDITION_CHANGE_LIST = 'STORAGE_CONDITION_CHANGE_LIST';
export const STORAGE_CONDITION_PUSH_LIST = 'STORAGE_CONDITION_PUSH_LIST';
export const STORAGE_CONDITION_REMOVE_LIST = 'STORAGE_CONDITION_REMOVE_LIST';
export const STORAGE_CONDITION_UPDATE_LIST = 'STORAGE_CONDITION_UPDATE_LIST';
export const STORAGE_CONDITION_CHANGE_SEARCH_LIST = 'STORAGE_CONDITION_CHANGE_SEARCH_LIST';
export const STORAGE_CONDITION_FILTER_LIST = 'STORAGE_CONDITION_FILTER_LIST';

export const STORAGE_CONDITION_CHANGE_DETAIL = 'STORAGE_CONDITION_CHANGE_DETAIL';