export const VALUE_ADDED_TAX_FORM_CHANGE = 'VALUE_ADDED_TAX_FORM_CHANGE';
export const VALUE_ADDED_TAX_FORM_VALIDATION = 'VALUE_ADDED_TAX_FORM_VALIDATION';
export const VALUE_ADDED_TAX_FORM_CLEAR = 'VALUE_ADDED_TAX_FORM_CLEAR';
export const VALUE_ADDED_TAX_FORM_CHANGE_MODE = 'VALUE_ADDED_TAX_FORM_CHANGE_MODE';

export const VALUE_ADDED_TAX_CHANGE_LIST = 'VALUE_ADDED_TAX_CHANGE_LIST';
export const VALUE_ADDED_TAX_PUSH_LIST = 'VALUE_ADDED_TAX_PUSH_LIST';
export const VALUE_ADDED_TAX_REMOVE_LIST = 'VALUE_ADDED_TAX_REMOVE_LIST';
export const VALUE_ADDED_TAX_UPDATE_LIST = 'VALUE_ADDED_TAX_UPDATE_LIST';
export const VALUE_ADDED_TAX_CHANGE_SEARCH_LIST = 'VALUE_ADDED_TAX_CHANGE_SEARCH_LIST';
export const VALUE_ADDED_TAX_FILTER_LIST = 'VALUE_ADDED_TAX_FILTER_LIST';

export const VALUE_ADDED_TAX_CHANGE_DETAIL = 'VALUE_ADDED_TAX_CHANGE_DETAIL';