export const MEDICINE_FORM_CHANGE = 'MEDICINE_FORM_CHANGE';
export const MEDICINE_FORM_VALIDATION = 'MEDICINE_FORM_VALIDATION';
export const MEDICINE_FORM_CLEAR = 'MEDICINE_FORM_CLEAR';
export const MEDICINE_FORM_CHANGE_MODE = 'MEDICINE_FORM_CHANGE_MODE';

export const MEDICINE_CHANGE_LIST = 'MEDICINE_CHANGE_LIST';
export const MEDICINE_PUSH_LIST = 'MEDICINE_PUSH_LIST';
export const MEDICINE_REMOVE_LIST = 'MEDICINE_REMOVE_LIST';
export const MEDICINE_UPDATE_LIST = 'MEDICINE_UPDATE_LIST';
export const MEDICINE_CHANGE_SEARCH_LIST = 'MEDICINE_CHANGE_SEARCH_LIST';
export const MEDICINE_CLEAR_SEARCH_LIST = 'MEDICINE_CLEAR_SEARCH_LIST';
export const MEDICINE_FILTER_LIST = 'MEDICINE_FILTER_LIST';

export const MEDICINE_CHANGE_DETAIL = 'MEDICINE_CHANGE_DETAIL';
export const MEDICINE_CHANGE_PRODUCT_INPUT_DETAIL = 'MEDICINE_CHANGE_PRODUCT_INPUT_DETAIL';