export const USER_FORM_CHANGE = 'USER_FORM_CHANGE';
export const USER_FORM_VALIDATION = 'USER_FORM_VALIDATION';
export const USER_FORM_CLEAR = 'USER_FORM_CLEAR';
export const USER_FORM_CHANGE_MODE = 'USER_FORM_CHANGE_MODE';

export const USER_CHANGE_LIST = 'USER_CHANGE_LIST';
export const USER_PUSH_LIST = 'USER_PUSH_LIST';
export const USER_REMOVE_LIST = 'USER_REMOVE_LIST';
export const USER_UPDATE_LIST = 'USER_UPDATE_LIST';
export const USER_CHANGE_SEARCH_LIST = 'USER_CHANGE_SEARCH_LIST';
export const USER_FILTER_LIST = 'USER_FILTER_LIST';

export const USER_CHANGE_DETAIL = 'USER_CHANGE_DETAIL';

export const CUSTOMER_CHANGE_LIST = 'CUSTOMER_CHANGE_LIST';