//TẢI LIST INTERNAL STOCK DELIVERY
export const PRESCRIPTION_RETAIL_CHANGE_LIST = 'PRESCRIPTION_RETAIL_CHANGE_LIST';
export const PRESCRIPTION_RETAIL_CHANGE_LIST_CHILD = 'PRESCRIPTION_RETAIL_CHANGE_LIST_CHILD';
export const PRESCRIPTION_RETAIL_CLEAR_LIST_CHILD = 'PRESCRIPTION_RETAIL_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const PRESCRIPTION_RETAIL_PUSH_LIST_CHILD = 'PRESCRIPTION_RETAIL_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const PRESCRIPTION_RETAIL_CHANGE_SELECTED_DETAIL = 'PRESCRIPTION_RETAIL_CHANGE_SELECTED_DETAIL';
export const PRESCRIPTION_RETAIL_CLEAR_SELECTED_DETAIL = 'PRESCRIPTION_RETAIL_CLEAR_SELECTED_DETAIL';
export const PRESCRIPTION_RETAIL_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'PRESCRIPTION_RETAIL_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const PRESCRIPTION_RETAIL_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'PRESCRIPTION_RETAIL_CLEAR_LIST_CHILD_SELECTED_DETAIL';

export const PRESCRIPTION_RETAIL_FORM_CHANGE = 'PRESCRIPTION_RETAIL_FORM_CHANGE';
export const PRESCRIPTION_RETAIL_FORM_VALIDATION = 'PRESCRIPTION_RETAIL_FORM_VALIDATION';
export const PRESCRIPTION_RETAIL_FORM_CHANGE_VALUES = 'PRESCRIPTION_RETAIL_FORM_CHANGE_VALUES';
export const PRESCRIPTION_RETAIL_FORM_CLEAR = 'PRESCRIPTION_RETAIL_FORM_CLEAR'; //CLEAR FORM CHA
export const PRESCRIPTION_RETAIL_CHANGE_MODE = 'PRESCRIPTION_RETAIL_CHANGE_MODE';

export const PRESCRIPTION_RETAIL_FORM_CHILD_CHANGE = 'PRESCRIPTION_RETAIL_FORM_CHILD_CHANGE';
export const PRESCRIPTION_RETAIL_FORM_CHILD_CHANGE_MODE = 'PRESCRIPTION_RETAIL_FORM_CHILD_CHANGE_MODE';
export const PRESCRIPTION_RETAIL_FORM_CHILD_CLEAR = 'PRESCRIPTION_RETAIL_FORM_CHILD_CLEAR';
export const PRESCRIPTION_RETAIL_FORM_CHILD_VALIDATION = 'PRESCRIPTION_RETAIL_FORM_CHILD_VALIDATION';
export const PRESCRIPTION_RETAIL_CHANGE_SEARCH_LIST = 'PRESCRIPTION_RETAIL_CHANGE_SEARCH_LIST';