export const SUPPLIER_GROUP_FORM_CHANGE = 'SUPPLIER_GROUP_FORM_CHANGE';
export const SUPPLIER_GROUP_FORM_VALIDATION = 'SUPPLIER_GROUP_FORM_VALIDATION';
export const SUPPLIER_GROUP_FORM_CLEAR = 'SUPPLIER_GROUP_FORM_CLEAR';
export const SUPPLIER_GROUP_FORM_CHANGE_MODE = 'SUPPLIER_GROUP_FORM_CHANGE_MODE';

export const SUPPLIER_GROUP_CHANGE_LIST = 'SUPPLIER_GROUP_CHANGE_LIST';
export const SUPPLIER_GROUP_PUSH_LIST = 'SUPPLIER_GROUP_PUSH_LIST';
export const SUPPLIER_GROUP_REMOVE_LIST = 'SUPPLIER_GROUP_REMOVE_LIST';
export const SUPPLIER_GROUP_UPDATE_LIST = 'SUPPLIER_GROUP_UPDATE_LIST';
export const SUPPLIER_GROUP_CHANGE_SEARCH_LIST = 'SUPPLIER_GROUP_CHANGE_SEARCH_LIST';
export const SUPPLIER_GROUP_FILTER_LIST = 'SUPPLIER_GROUP_FILTER_LIST';

export const SUPPLIER_GROUP_CHANGE_DETAIL = 'SUPPLIER_GROUP_CHANGE_DETAIL';