export const SICK_FORM_CHANGE = 'SICK_FORM_CHANGE';
export const SICK_FORM_VALIDATION = 'SICK_FORM_VALIDATION';
export const SICK_FORM_CLEAR = 'SICK_FORM_CLEAR';
export const SICK_FORM_CHANGE_MODE = 'SICK_FORM_CHANGE_MODE';

export const SICK_CHANGE_LIST = 'SICK_CHANGE_LIST';
export const SICK_PUSH_LIST = 'SICK_PUSH_LIST';
export const SICK_REMOVE_LIST = 'SICK_REMOVE_LIST';
export const SICK_UPDATE_LIST = 'SICK_UPDATE_LIST';
export const SICK_CHANGE_SEARCH_LIST = 'SICK_CHANGE_SEARCH_LIST';
export const SICK_FILTER_LIST = 'SICK_FILTER_LIST';

export const SICK_CHANGE_DETAIL = 'SICK_CHANGE_DETAIL';