//TẢI LIST INTERNAL STOCK DELIVERY
export const QUAN_LY_CONG_NO_CHANGE_LIST = 'QUAN_LY_CONG_NO_CHANGE_LIST';
export const QUAN_LY_CONG_NO_CHANGE_LIST_CHILD = 'QUAN_LY_CONG_NO_CHANGE_LIST_CHILD';
export const QUAN_LY_CONG_NO_CLEAR_LIST_CHILD = 'QUAN_LY_CONG_NO_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const QUAN_LY_CONG_NO_PUSH_LIST_CHILD = 'QUAN_LY_CONG_NO_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const QUAN_LY_CONG_NO_CHANGE_SELECTED_DETAIL = 'QUAN_LY_CONG_NO_CHANGE_SELECTED_DETAIL';
export const QUAN_LY_CONG_NO_CLEAR_SELECTED_DETAIL = 'QUAN_LY_CONG_NO_CLEAR_SELECTED_DETAIL';
export const QUAN_LY_CONG_NO_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'QUAN_LY_CONG_NO_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const QUAN_LY_CONG_NO_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'QUAN_LY_CONG_NO_CLEAR_LIST_CHILD_SELECTED_DETAIL';
export const QUAN_LY_CONG_NO_CHANGE_SEARCH_LIST = 'QUAN_LY_CONG_NO_CHANGE_SEARCH_LIST';

export const QUAN_LY_CONG_NO_FORM_CHANGE = 'QUAN_LY_CONG_NO_FORM_CHANGE';
export const QUAN_LY_CONG_NO_FORM_VALIDATION = 'QUAN_LY_CONG_NO_FORM_VALIDATION';
export const QUAN_LY_CONG_NO_FORM_CHANGE_VALUES = 'QUAN_LY_CONG_NO_FORM_CHANGE_VALUES';
export const QUAN_LY_CONG_NO_FORM_CLEAR = 'QUAN_LY_CONG_NO_FORM_CLEAR'; //CLEAR FORM CHA
export const QUAN_LY_CONG_NO_CHANGE_MODE = 'QUAN_LY_CONG_NO_CHANGE_MODE';

export const QUAN_LY_CONG_NO_FORM_CHILD_CHANGE = 'QUAN_LY_CONG_NO_FORM_CHILD_CHANGE';
export const QUAN_LY_CONG_NO_FORM_CHILD_CHANGE_MODE = 'QUAN_LY_CONG_NO_FORM_CHILD_CHANGE_MODE';
export const QUAN_LY_CONG_NO_FORM_CHILD_CLEAR = 'QUAN_LY_CONG_NO_FORM_CHILD_CLEAR';
export const QUAN_LY_CONG_NO_FORM_CHILD_VALIDATION = 'QUAN_LY_CONG_NO_FORM_CHILD_VALIDATION';