export const PHARMACY_WAREHOUSE_FORM_CHANGE = 'PHARMACY_WAREHOUSE_FORM_CHANGE';
export const PHARMACY_WAREHOUSE_FORM_VALIDATION = 'PHARMACY_WAREHOUSE_FORM_VALIDATION';
export const PHARMACY_WAREHOUSE_FORM_CLEAR = 'PHARMACY_WAREHOUSE_FORM_CLEAR';
export const PHARMACY_WAREHOUSE_FORM_CHANGE_MODE = 'PHARMACY_WAREHOUSE_FORM_CHANGE_MODE';

export const PHARMACY_WAREHOUSE_CHANGE_LIST = 'PHARMACY_WAREHOUSE_CHANGE_LIST';
export const PHARMACY_WAREHOUSE_PUSH_LIST = 'PHARMACY_WAREHOUSE_PUSH_LIST';
export const PHARMACY_WAREHOUSE_REMOVE_LIST = 'PHARMACY_WAREHOUSE_REMOVE_LIST';
export const PHARMACY_WAREHOUSE_UPDATE_LIST = 'PHARMACY_WAREHOUSE_UPDATE_LIST';
export const PHARMACY_WAREHOUSE_CHANGE_SEARCH_LIST = 'PHARMACY_WAREHOUSE_CHANGE_SEARCH_LIST';
export const PHARMACY_WAREHOUSE_FILTER_LIST = 'PHARMACY_WAREHOUSE_FILTER_LIST';

export const PHARMACY_WAREHOUSE_CHANGE_DETAIL = 'PHARMACY_WAREHOUSE_CHANGE_DETAIL';