export const INPUT_OUTPUT_TYPE_FORM_FORM_CHANGE = 'INPUT_OUTPUT_TYPE_FORM_FORM_CHANGE';
export const INPUT_OUTPUT_TYPE_FORM_FORM_VALIDATION = 'INPUT_OUTPUT_TYPE_FORM_FORM_VALIDATION';
export const INPUT_OUTPUT_TYPE_FORM_FORM_CLEAR = 'INPUT_OUTPUT_TYPE_FORM_FORM_CLEAR';
export const INPUT_OUTPUT_TYPE_FORM_FORM_CHANGE_MODE = 'INPUT_OUTPUT_TYPE_FORM_FORM_CHANGE_MODE';

export const INPUT_OUTPUT_TYPE_FORM_CHANGE_LIST = 'INPUT_OUTPUT_TYPE_FORM_CHANGE_LIST';
export const INPUT_OUTPUT_TYPE_FORM_PUSH_LIST = 'INPUT_OUTPUT_TYPE_FORM_PUSH_LIST';
export const INPUT_OUTPUT_TYPE_FORM_REMOVE_LIST = 'INPUT_OUTPUT_TYPE_FORM_REMOVE_LIST';
export const INPUT_OUTPUT_TYPE_FORM_UPDATE_LIST = 'INPUT_OUTPUT_TYPE_FORM_UPDATE_LIST';
export const INPUT_OUTPUT_TYPE_FORM_CHANGE_SEARCH_LIST = 'INPUT_OUTPUT_TYPE_FORM_CHANGE_SEARCH_LIST';
export const INPUT_OUTPUT_TYPE_FORM_FILTER_LIST = 'INPUT_OUTPUT_TYPE_FORM_FILTER_LIST';

export const INPUT_OUTPUT_TYPE_FORM_CHANGE_DETAIL = 'INPUT_OUTPUT_TYPE_FORM_CHANGE_DETAIL';