//TẢI LIST INTERNAL STOCK DELIVERY
export const THE_KHO_CHANGE_LIST = 'THE_KHO_CHANGE_LIST';
export const THE_KHO_CHANGE_LIST_CHILD = 'THE_KHO_CHANGE_LIST_CHILD';
export const THE_KHO_CLEAR_LIST_CHILD = 'THE_KHO_CLEAR_LIST_CHILD';
export const THE_KHO_CLEAR_LIST = 'THE_KHO_CLEAR_LIST';
//THÊM VÀO LIST CHILD
export const THE_KHO_PUSH_LIST_CHILD = 'THE_KHO_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const THE_KHO_CHANGE_SELECTED_DETAIL = 'THE_KHO_CHANGE_SELECTED_DETAIL';
export const THE_KHO_CLEAR_SELECTED_DETAIL = 'THE_KHO_CLEAR_SELECTED_DETAIL';
export const THE_KHO_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'THE_KHO_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const THE_KHO_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'THE_KHO_CLEAR_LIST_CHILD_SELECTED_DETAIL';
export const THE_KHO_CHANGE_SEARCH_LIST = 'THE_KHO_CHANGE_SEARCH_LIST';

export const THE_KHO_FORM_CHANGE = 'THE_KHO_FORM_CHANGE';
export const THE_KHO_FORM_VALIDATION = 'THE_KHO_FORM_VALIDATION';
export const THE_KHO_FORM_CHANGE_VALUES = 'THE_KHO_FORM_CHANGE_VALUES';
export const THE_KHO_FORM_CLEAR = 'THE_KHO_FORM_CLEAR'; //CLEAR FORM CHA
export const THE_KHO_CHANGE_MODE = 'THE_KHO_CHANGE_MODE';

export const THE_KHO_FORM_CHILD_CHANGE = 'THE_KHO_FORM_CHILD_CHANGE';
export const THE_KHO_FORM_CHILD_CHANGE_MODE = 'THE_KHO_FORM_CHILD_CHANGE_MODE';
export const THE_KHO_FORM_CHILD_CLEAR = 'THE_KHO_FORM_CHILD_CLEAR';
export const THE_KHO_FORM_CHILD_VALIDATION = 'THE_KHO_FORM_CHILD_VALIDATION';