export const PRODUCER_FORM_CHANGE = 'PRODUCER_FORM_CHANGE';
export const PRODUCER_FORM_VALIDATION = 'PRODUCER_FORM_VALIDATION';
export const PRODUCER_FORM_CLEAR = 'PRODUCER_FORM_CLEAR';
export const PRODUCER_FORM_CHANGE_MODE = 'PRODUCER_FORM_CHANGE_MODE';

export const PRODUCER_CHANGE_LIST = 'PRODUCER_CHANGE_LIST';
export const PRODUCER_PUSH_LIST = 'PRODUCER_PUSH_LIST';
export const PRODUCER_REMOVE_LIST = 'PRODUCER_REMOVE_LIST';
export const PRODUCER_UPDATE_LIST = 'PRODUCER_UPDATE_LIST';
export const PRODUCER_CHANGE_SEARCH_LIST = 'PRODUCER_CHANGE_SEARCH_LIST';
export const PRODUCER_FILTER_LIST = 'PRODUCER_FILTER_LIST';

export const PRODUCER_CHANGE_DETAIL = 'PRODUCER_CHANGE_DETAIL';