export const DEPARTMENT_MEDICINE_FORM_CHANGE = 'DEPARTMENT_MEDICINE_FORM_CHANGE';
export const DEPARTMENT_MEDICINE_FORM_VALIDATION = 'DEPARTMENT_MEDICINE_FORM_VALIDATION';
export const DEPARTMENT_MEDICINE_FORM_CLEAR = 'DEPARTMENT_MEDICINE_FORM_CLEAR';
export const DEPARTMENT_MEDICINE_FORM_CHANGE_MODE = 'DEPARTMENT_MEDICINE_FORM_CHANGE_MODE';

export const DEPARTMENT_MEDICINE_CHANGE_LIST = 'DEPARTMENT_MEDICINE_CHANGE_LIST';
export const DEPARTMENT_MEDICINE_PUSH_LIST = 'DEPARTMENT_MEDICINE_PUSH_LIST';
export const DEPARTMENT_MEDICINE_REMOVE_LIST = 'DEPARTMENT_MEDICINE_REMOVE_LIST';
export const DEPARTMENT_MEDICINE_UPDATE_LIST = 'DEPARTMENT_MEDICINE_UPDATE_LIST';
export const DEPARTMENT_MEDICINE_CHANGE_SEARCH_LIST = 'DEPARTMENT_MEDICINE_CHANGE_SEARCH_LIST';
export const DEPARTMENT_MEDICINE_FILTER_LIST = 'DEPARTMENT_MEDICINE_FILTER_LIST';
export const DEPARTMENT_MEDICINE_CHANGE_DOCTORS = 'DEPARTMENT_MEDICINE_CHANGE_DOCTORS';
export const DEPARTMENT_MEDICINE_CLEAR_DOCTORS = 'DEPARTMENT_MEDICINE_CLEAR_DOCTORS';

export const DEPARTMENT_MEDICINE_CHANGE_DETAIL = 'DEPARTMENT_MEDICINE_CHANGE_DETAIL';