export const RETAIL_CUSTOMER_FORM_CHANGE = 'RETAIL_CUSTOMER_FORM_CHANGE';
export const RETAIL_CUSTOMER_FORM_VALIDATION = 'RETAIL_CUSTOMER_FORM_VALIDATION';
export const RETAIL_CUSTOMER_FORM_CLEAR = 'RETAIL_CUSTOMER_FORM_CLEAR';
export const RETAIL_CUSTOMER_FORM_CHANGE_MODE = 'RETAIL_CUSTOMER_FORM_CHANGE_MODE';

export const RETAIL_CUSTOMER_CHANGE_LIST = 'RETAIL_CUSTOMER_CHANGE_LIST';
export const RETAIL_CUSTOMER_PUSH_LIST = 'RETAIL_CUSTOMER_PUSH_LIST';
export const RETAIL_CUSTOMER_REMOVE_LIST = 'RETAIL_CUSTOMER_REMOVE_LIST';
export const RETAIL_CUSTOMER_UPDATE_LIST = 'RETAIL_CUSTOMER_UPDATE_LIST';
export const RETAIL_CUSTOMER_CHANGE_SEARCH_LIST = 'RETAIL_CUSTOMER_CHANGE_SEARCH_LIST';
export const RETAIL_CUSTOMER_FILTER_LIST = 'RETAIL_CUSTOMER_FILTER_LIST';

export const RETAIL_CUSTOMER_CHANGE_DETAIL = 'RETAIL_CUSTOMER_CHANGE_DETAIL';