//TẢI LIST INTERNAL STOCK DELIVERY
export const XUAT_CHUYEN_KHO_CHANGE_LIST = 'XUAT_CHUYEN_KHO_CHANGE_LIST';
export const XUAT_CHUYEN_KHO_CHANGE_LIST_CHILD = 'XUAT_CHUYEN_KHO_CHANGE_LIST_CHILD';
export const XUAT_CHUYEN_KHO_CLEAR_LIST_CHILD = 'XUAT_CHUYEN_KHO_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const XUAT_CHUYEN_KHO_PUSH_LIST_CHILD = 'XUAT_CHUYEN_KHO_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const XUAT_CHUYEN_KHO_CHANGE_SELECTED_DETAIL = 'XUAT_CHUYEN_KHO_CHANGE_SELECTED_DETAIL';
export const XUAT_CHUYEN_KHO_CLEAR_SELECTED_DETAIL = 'XUAT_CHUYEN_KHO_CLEAR_SELECTED_DETAIL';
export const XUAT_CHUYEN_KHO_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'XUAT_CHUYEN_KHO_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const XUAT_CHUYEN_KHO_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'XUAT_CHUYEN_KHO_CLEAR_LIST_CHILD_SELECTED_DETAIL';

export const XUAT_CHUYEN_KHO_FORM_CHANGE = 'XUAT_CHUYEN_KHO_FORM_CHANGE';
export const XUAT_CHUYEN_KHO_FORM_VALIDATION = 'XUAT_CHUYEN_KHO_FORM_VALIDATION';
export const XUAT_CHUYEN_KHO_FORM_CHANGE_VALUES = 'XUAT_CHUYEN_KHO_FORM_CHANGE_VALUES';
export const XUAT_CHUYEN_KHO_FORM_CLEAR = 'XUAT_CHUYEN_KHO_FORM_CLEAR'; //CLEAR FORM CHA
export const XUAT_CHUYEN_KHO_CHANGE_MODE = 'XUAT_CHUYEN_KHO_CHANGE_MODE';

export const XUAT_CHUYEN_KHO_FORM_CHILD_CHANGE = 'XUAT_CHUYEN_KHO_FORM_CHILD_CHANGE';
export const XUAT_CHUYEN_KHO_FORM_CHILD_CHANGE_MODE = 'XUAT_CHUYEN_KHO_FORM_CHILD_CHANGE_MODE';
export const XUAT_CHUYEN_KHO_FORM_CHILD_CLEAR = 'XUAT_CHUYEN_KHO_FORM_CHILD_CLEAR';
export const XUAT_CHUYEN_KHO_FORM_CHILD_VALIDATION = 'XUAT_CHUYEN_KHO_FORM_CHILD_VALIDATION';
export const XUAT_CHUYEN_KHO_FORM_CHILD_UPDATE_LIST = 'XUAT_CHUYEN_KHO_FORM_CHILD_UPDATE_LIST'; // Update list child