export const MATERIAL_FORM_CHANGE = 'MATERIAL_FORM_CHANGE';
export const MATERIAL_FORM_VALIDATION = 'MATERIAL_FORM_VALIDATION';
export const MATERIAL_FORM_CLEAR = 'MATERIAL_FORM_CLEAR';
export const MATERIAL_FORM_CHANGE_MODE = 'MATERIAL_FORM_CHANGE_MODE';

export const MATERIAL_CHANGE_LIST = 'MATERIAL_CHANGE_LIST';
export const MATERIAL_PUSH_LIST = 'MATERIAL_PUSH_LIST';
export const MATERIAL_REMOVE_LIST = 'MATERIAL_REMOVE_LIST';
export const MATERIAL_UPDATE_LIST = 'MATERIAL_UPDATE_LIST';
export const MATERIAL_CHANGE_SEARCH_LIST = 'MATERIAL_CHANGE_SEARCH_LIST';
export const MATERIAL_FILTER_LIST = 'MATERIAL_FILTER_LIST';

export const MATERIAL_CHANGE_DETAIL = 'MATERIAL_CHANGE_DETAIL';