export const STORAGE_POSITION_FORM_CHANGE = 'STORAGE_POSITION_FORM_CHANGE';
export const STORAGE_POSITION_FORM_VALIDATION = 'STORAGE_POSITION_FORM_VALIDATION';
export const STORAGE_POSITION_FORM_CLEAR = 'STORAGE_POSITION_FORM_CLEAR';
export const STORAGE_POSITION_FORM_CHANGE_MODE = 'STORAGE_POSITION_FORM_CHANGE_MODE';

export const STORAGE_POSITION_CHANGE_LIST = 'STORAGE_POSITION_CHANGE_LIST';
export const STORAGE_POSITION_PUSH_LIST = 'STORAGE_POSITION_PUSH_LIST';
export const STORAGE_POSITION_REMOVE_LIST = 'STORAGE_POSITION_REMOVE_LIST';
export const STORAGE_POSITION_UPDATE_LIST = 'STORAGE_POSITION_UPDATE_LIST';
export const STORAGE_POSITION_CHANGE_SEARCH_LIST = 'STORAGE_POSITION_CHANGE_SEARCH_LIST';
export const STORAGE_POSITION_FILTER_LIST = 'STORAGE_POSITION_FILTER_LIST';

export const STORAGE_POSITION_CHANGE_DETAIL = 'STORAGE_POSITION_CHANGE_DETAIL';