export const COUNTRY_FORM_CHANGE = 'COUNTRY_FORM_CHANGE';
export const COUNTRY_FORM_VALIDATION = 'COUNTRY_FORM_VALIDATION';
export const COUNTRY_FORM_CLEAR = 'COUNTRY_FORM_CLEAR';
export const COUNTRY_FORM_CHANGE_MODE = 'COUNTRY_FORM_CHANGE_MODE';

export const COUNTRY_CHANGE_LIST = 'COUNTRY_CHANGE_LIST';
export const COUNTRY_PUSH_LIST = 'COUNTRY_PUSH_LIST';
export const COUNTRY_REMOVE_LIST = 'COUNTRY_REMOVE_LIST';
export const COUNTRY_UPDATE_LIST = 'COUNTRY_UPDATE_LIST';
export const COUNTRY_CHANGE_SEARCH_LIST = 'COUNTRY_CHANGE_SEARCH_LIST';
export const COUNTRY_FILTER_LIST = 'COUNTRY_FILTER_LIST';

export const COUNTRY_CHANGE_DETAIL = 'COUNTRY_CHANGE_DETAIL';