export const DRUG_STORE_FORM_CHANGE = 'DRUG_STORE_FORM_CHANGE';
export const DRUG_STORE_FORM_VALIDATION = 'DRUG_STORE_FORM_VALIDATION';
export const DRUG_STORE_FORM_CLEAR = 'DRUG_STORE_FORM_CLEAR';
export const DRUG_STORE_FORM_CHANGE_MODE = 'DRUG_STORE_FORM_CHANGE_MODE';

export const DRUG_STORE_CHANGE_LIST = 'DRUG_STORE_CHANGE_LIST';
export const DRUG_STORE_PUSH_LIST = 'DRUG_STORE_PUSH_LIST';
export const DRUG_STORE_REMOVE_LIST = 'DRUG_STORE_REMOVE_LIST';
export const DRUG_STORE_UPDATE_LIST = 'DRUG_STORE_UPDATE_LIST';
export const DRUG_STORE_CHANGE_SEARCH_LIST = 'DRUG_STORE_CHANGE_SEARCH_LIST';
export const DRUG_STORE_FILTER_LIST = 'DRUG_STORE_FILTER_LIST';

export const DRUG_STORE_CHANGE_DETAIL = 'DRUG_STORE_CHANGE_DETAIL';