//TẢI LIST INTERNAL STOCK DELIVERY
export const PHIEU_CHI_CHANGE_LIST = 'PHIEU_CHI_CHANGE_LIST';
export const PHIEU_CHI_CHANGE_LIST_CHILD = 'PHIEU_CHI_CHANGE_LIST_CHILD';
export const PHIEU_CHI_CLEAR_LIST_CHILD = 'PHIEU_CHI_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const PHIEU_CHI_PUSH_LIST_CHILD = 'PHIEU_CHI_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const PHIEU_CHI_CHANGE_SELECTED_DETAIL = 'PHIEU_CHI_CHANGE_SELECTED_DETAIL';
export const PHIEU_CHI_CLEAR_SELECTED_DETAIL = 'PHIEU_CHI_CLEAR_SELECTED_DETAIL';
export const PHIEU_CHI_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'PHIEU_CHI_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const PHIEU_CHI_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'PHIEU_CHI_CLEAR_LIST_CHILD_SELECTED_DETAIL';
export const PHIEU_CHI_CHANGE_SEARCH_LIST = 'PHIEU_CHI_CHANGE_SEARCH_LIST';

export const PHIEU_CHI_FORM_CHANGE = 'PHIEU_CHI_FORM_CHANGE';
export const PHIEU_CHI_FORM_VALIDATION = 'PHIEU_CHI_FORM_VALIDATION';
export const PHIEU_CHI_FORM_CHANGE_VALUES = 'PHIEU_CHI_FORM_CHANGE_VALUES';
export const PHIEU_CHI_FORM_CLEAR = 'PHIEU_CHI_FORM_CLEAR'; //CLEAR FORM CHA
export const PHIEU_CHI_CHANGE_MODE = 'PHIEU_CHI_CHANGE_MODE';

export const PHIEU_CHI_FORM_CHILD_CHANGE = 'PHIEU_CHI_FORM_CHILD_CHANGE';
export const PHIEU_CHI_FORM_CHILD_CHANGE_MODE = 'PHIEU_CHI_FORM_CHILD_CHANGE_MODE';
export const PHIEU_CHI_FORM_CHILD_CLEAR = 'PHIEU_CHI_FORM_CHILD_CLEAR';
export const PHIEU_CHI_FORM_CHILD_VALIDATION = 'PHIEU_CHI_FORM_CHILD_VALIDATION';