//TẢI LIST INTERNAL STOCK DELIVERY
export const PHIEU_THU_CHANGE_LIST = 'PHIEU_THU_CHANGE_LIST';
export const PHIEU_THU_CHANGE_LIST_CHILD = 'PHIEU_THU_CHANGE_LIST_CHILD';
export const PHIEU_THU_CLEAR_LIST_CHILD = 'PHIEU_THU_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const PHIEU_THU_PUSH_LIST_CHILD = 'PHIEU_THU_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const PHIEU_THU_CHANGE_SELECTED_DETAIL = 'PHIEU_THU_CHANGE_SELECTED_DETAIL';
export const PHIEU_THU_CLEAR_SELECTED_DETAIL = 'PHIEU_THU_CLEAR_SELECTED_DETAIL';
export const PHIEU_THU_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'PHIEU_THU_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const PHIEU_THU_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'PHIEU_THU_CLEAR_LIST_CHILD_SELECTED_DETAIL';
export const PHIEU_THU_CHANGE_SEARCH_LIST = 'PHIEU_THU_CHANGE_SEARCH_LIST';

export const PHIEU_THU_FORM_CHANGE = 'PHIEU_THU_FORM_CHANGE';
export const PHIEU_THU_FORM_VALIDATION = 'PHIEU_THU_FORM_VALIDATION';
export const PHIEU_THU_FORM_CHANGE_VALUES = 'PHIEU_THU_FORM_CHANGE_VALUES';
export const PHIEU_THU_FORM_CLEAR = 'PHIEU_THU_FORM_CLEAR'; //CLEAR FORM CHA
export const PHIEU_THU_CHANGE_MODE = 'PHIEU_THU_CHANGE_MODE';

export const PHIEU_THU_FORM_CHILD_CHANGE = 'PHIEU_THU_FORM_CHILD_CHANGE';
export const PHIEU_THU_FORM_CHILD_CHANGE_MODE = 'PHIEU_THU_FORM_CHILD_CHANGE_MODE';
export const PHIEU_THU_FORM_CHILD_CLEAR = 'PHIEU_THU_FORM_CHILD_CLEAR';
export const PHIEU_THU_FORM_CHILD_VALIDATION = 'PHIEU_THU_FORM_CHILD_VALIDATION';