export const BEGIN_LIABILITY_FORM_CHANGE = 'BEGIN_LIABILITY_FORM_CHANGE';
export const BEGIN_LIABILITY_FORM_VALIDATION = 'BEGIN_LIABILITY_FORM_VALIDATION';
export const BEGIN_LIABILITY_FORM_CLEAR = 'BEGIN_LIABILITY_FORM_CLEAR';
export const BEGIN_LIABILITY_FORM_CHANGE_MODE = 'BEGIN_LIABILITY_FORM_CHANGE_MODE';

export const BEGIN_LIABILITY_CHANGE_LIST = 'BEGIN_LIABILITY_CHANGE_LIST';
export const BEGIN_LIABILITY_PUSH_LIST = 'BEGIN_LIABILITY_PUSH_LIST';
export const BEGIN_LIABILITY_REMOVE_LIST = 'BEGIN_LIABILITY_REMOVE_LIST';
export const BEGIN_LIABILITY_UPDATE_LIST = 'BEGIN_LIABILITY_UPDATE_LIST';
export const BEGIN_LIABILITY_CHANGE_SEARCH_LIST = 'BEGIN_LIABILITY_CHANGE_SEARCH_LIST';
export const BEGIN_LIABILITY_FILTER_LIST = 'BEGIN_LIABILITY_FILTER_LIST';

export const BEGIN_LIABILITY_CHANGE_DETAIL = 'BEGIN_LIABILITY_CHANGE_DETAIL';