//TẢI LIST INTERNAL STOCK DELIVERY
export const BAO_CAO_XUAT_NHAP_TON_CHANGE_LIST = 'BAO_CAO_XUAT_NHAP_TON_CHANGE_LIST';
export const BAO_CAO_XUAT_NHAP_TON_CHANGE_LIST_CHILD = 'BAO_CAO_XUAT_NHAP_TON_CHANGE_LIST_CHILD';
export const BAO_CAO_XUAT_NHAP_TON_CLEAR_LIST_CHILD = 'BAO_CAO_XUAT_NHAP_TON_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const BAO_CAO_XUAT_NHAP_TON_PUSH_LIST_CHILD = 'BAO_CAO_XUAT_NHAP_TON_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const BAO_CAO_XUAT_NHAP_TON_CHANGE_SELECTED_DETAIL = 'BAO_CAO_XUAT_NHAP_TON_CHANGE_SELECTED_DETAIL';
export const BAO_CAO_XUAT_NHAP_TON_CLEAR_SELECTED_DETAIL = 'BAO_CAO_XUAT_NHAP_TON_CLEAR_SELECTED_DETAIL';
export const BAO_CAO_XUAT_NHAP_TON_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'BAO_CAO_XUAT_NHAP_TON_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const BAO_CAO_XUAT_NHAP_TON_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'BAO_CAO_XUAT_NHAP_TON_CLEAR_LIST_CHILD_SELECTED_DETAIL';
export const BAO_CAO_XUAT_NHAP_TON_CHANGE_SEARCH_LIST = 'BAO_CAO_XUAT_NHAP_TON_CHANGE_SEARCH_LIST';

export const BAO_CAO_XUAT_NHAP_TON_FORM_CHANGE = 'BAO_CAO_XUAT_NHAP_TON_FORM_CHANGE';
export const BAO_CAO_XUAT_NHAP_TON_FORM_VALIDATION = 'BAO_CAO_XUAT_NHAP_TON_FORM_VALIDATION';
export const BAO_CAO_XUAT_NHAP_TON_FORM_CHANGE_VALUES = 'BAO_CAO_XUAT_NHAP_TON_FORM_CHANGE_VALUES';
export const BAO_CAO_XUAT_NHAP_TON_FORM_CLEAR = 'BAO_CAO_XUAT_NHAP_TON_FORM_CLEAR'; //CLEAR FORM CHA
export const BAO_CAO_XUAT_NHAP_TON_CHANGE_MODE = 'BAO_CAO_XUAT_NHAP_TON_CHANGE_MODE';

export const BAO_CAO_XUAT_NHAP_TON_FORM_CHILD_CHANGE = 'BAO_CAO_XUAT_NHAP_TON_FORM_CHILD_CHANGE';
export const BAO_CAO_XUAT_NHAP_TON_FORM_CHILD_CHANGE_MODE = 'BAO_CAO_XUAT_NHAP_TON_FORM_CHILD_CHANGE_MODE';
export const BAO_CAO_XUAT_NHAP_TON_FORM_CHILD_CLEAR = 'BAO_CAO_XUAT_NHAP_TON_FORM_CHILD_CLEAR';
export const BAO_CAO_XUAT_NHAP_TON_FORM_CHILD_VALIDATION = 'BAO_CAO_XUAT_NHAP_TON_FORM_CHILD_VALIDATION';