//TẢI LIST INTERNAL STOCK DELIVERY
export const RETAILER_CHANGE_LIST = 'RETAILER_CHANGE_LIST';
export const RETAILER_CHANGE_SEARCH_HOA_DON_LIST = 'RETAILER_CHANGE_SEARCH_HOA_DON_LIST';
export const RETAILER_CHANGE_LIST_CHILD = 'RETAILER_CHANGE_LIST_CHILD';
export const RETAILER_CLEAR_LIST_CHILD = 'RETAILER_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const RETAILER_PUSH_LIST_CHILD = 'RETAILER_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const RETAILER_CHANGE_SELECTED_DETAIL = 'RETAILER_CHANGE_SELECTED_DETAIL';
export const RETAILER_CLEAR_SELECTED_DETAIL = 'RETAILER_CLEAR_SELECTED_DETAIL';
export const RETAILER_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'RETAILER_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const RETAILER_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'RETAILER_CLEAR_LIST_CHILD_SELECTED_DETAIL';
export const RETAILER_CHANGE_SEARCH_LIST = 'RETAILER_CHANGE_SEARCH_LIST';

export const RETAILER_FORM_CHANGE = 'RETAILER_FORM_CHANGE';
export const RETAILER_FORM_VALIDATION = 'RETAILER_FORM_VALIDATION';
export const RETAILER_FORM_CHANGE_VALUES = 'RETAILER_FORM_CHANGE_VALUES';
export const RETAILER_FORM_CLEAR = 'RETAILER_FORM_CLEAR'; //CLEAR FORM CHA
export const RETAILER_CHANGE_MODE = 'RETAILER_CHANGE_MODE';

export const RETAILER_FORM_CHILD_CHANGE = 'RETAILER_FORM_CHILD_CHANGE';
export const RETAILER_FORM_CHILD_CHANGE_MODE = 'RETAILER_FORM_CHILD_CHANGE_MODE';
export const RETAILER_FORM_CHILD_CLEAR = 'RETAILER_FORM_CHILD_CLEAR';
export const RETAILER_FORM_CHILD_VALIDATION = 'RETAILER_FORM_CHILD_VALIDATION';