//TẢI LIST INTERNAL STOCK DELIVERY
export const XUAT_TRA_HANG_NCC_CHANGE_LIST = 'XUAT_TRA_HANG_NCC_CHANGE_LIST';
export const XUAT_TRA_HANG_NCC_CHANGE_LIST_CHILD = 'XUAT_TRA_HANG_NCC_CHANGE_LIST_CHILD';
export const XUAT_TRA_HANG_NCC_CLEAR_LIST_CHILD = 'XUAT_TRA_HANG_NCC_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const XUAT_TRA_HANG_NCC_PUSH_LIST_CHILD = 'XUAT_TRA_HANG_NCC_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const XUAT_TRA_HANG_NCC_CHANGE_SELECTED_DETAIL = 'XUAT_TRA_HANG_NCC_CHANGE_SELECTED_DETAIL';
export const XUAT_TRA_HANG_NCC_CLEAR_SELECTED_DETAIL = 'XUAT_TRA_HANG_NCC_CLEAR_SELECTED_DETAIL';
export const XUAT_TRA_HANG_NCC_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'XUAT_TRA_HANG_NCC_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const XUAT_TRA_HANG_NCC_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'XUAT_TRA_HANG_NCC_CLEAR_LIST_CHILD_SELECTED_DETAIL';

export const XUAT_TRA_HANG_NCC_FORM_CHANGE = 'XUAT_TRA_HANG_NCC_FORM_CHANGE';
export const XUAT_TRA_HANG_NCC_FORM_VALIDATION = 'XUAT_TRA_HANG_NCC_FORM_VALIDATION';
export const XUAT_TRA_HANG_NCC_FORM_CHANGE_VALUES = 'XUAT_TRA_HANG_NCC_FORM_CHANGE_VALUES';
export const XUAT_TRA_HANG_NCC_FORM_CLEAR = 'XUAT_TRA_HANG_NCC_FORM_CLEAR'; //CLEAR FORM CHA
export const XUAT_TRA_HANG_NCC_CHANGE_MODE = 'XUAT_TRA_HANG_NCC_CHANGE_MODE';

export const XUAT_TRA_HANG_NCC_FORM_CHILD_CHANGE = 'XUAT_TRA_HANG_NCC_FORM_CHILD_CHANGE';
export const XUAT_TRA_HANG_NCC_FORM_CHILD_CHANGE_MODE = 'XUAT_TRA_HANG_NCC_FORM_CHILD_CHANGE_MODE';
export const XUAT_TRA_HANG_NCC_FORM_CHILD_CLEAR = 'XUAT_TRA_HANG_NCC_FORM_CHILD_CLEAR';
export const XUAT_TRA_HANG_NCC_FORM_CHILD_VALIDATION = 'XUAT_TRA_HANG_NCC_FORM_CHILD_VALIDATION';
export const XUAT_TRA_HANG_NCC_CHANGE_SEARCH_LIST = 'XUAT_TRA_HANG_NCC_CHANGE_SEARCH_LIST';
export const XUAT_TRA_HANG_NCC_CHANGE_CHANGE_DISABLED = 'XUAT_TRA_HANG_NCC_CHANGE_CHANGE_DISABLED';

// Search list 
export const XUAT_TRA_HANG_NCC_CHANGE_SEARCH_RESULT_LIST = 'XUAT_TRA_HANG_NCC_CHANGE_SEARCH_RESULT_LIST';
export const XUAT_TRA_HANG_NCC_CHANGE_SEARCH_RESULT_SELECTED_DETAIL = 'XUAT_TRA_HANG_NCC_CHANGE_SEARCH_RESULT_SELECTED_DETAIL';
// End search list