export const CUSTOMER_FORM_CHANGE = 'CUSTOMER_FORM_CHANGE';
export const CUSTOMER_FORM_VALIDATION = 'CUSTOMER_FORM_VALIDATION';
export const CUSTOMER_FORM_CLEAR = 'CUSTOMER_FORM_CLEAR';
export const CUSTOMER_FORM_CHANGE_MODE = 'CUSTOMER_FORM_CHANGE_MODE';

export const CUSTOMER_CHANGE_LIST = 'CUSTOMER_CHANGE_LIST';
export const CUSTOMER_PUSH_LIST = 'CUSTOMER_PUSH_LIST';
export const CUSTOMER_REMOVE_LIST = 'CUSTOMER_REMOVE_LIST';
export const CUSTOMER_UPDATE_LIST = 'CUSTOMER_UPDATE_LIST';
export const CUSTOMER_CHANGE_SEARCH_LIST = 'CUSTOMER_CHANGE_SEARCH_LIST';
export const CUSTOMER_FILTER_LIST = 'CUSTOMER_FILTER_LIST';

export const CUSTOMER_CHANGE_DETAIL = 'CUSTOMER_CHANGE_DETAIL';