export const MEDICINE_WARNING_FORM_CHANGE = 'MEDICINE_WARNING_FORM_CHANGE';
export const MEDICINE_WARNING_FORM_VALIDATION = 'MEDICINE_WARNING_FORM_VALIDATION';
export const MEDICINE_WARNING_FORM_CLEAR = 'MEDICINE_WARNING_FORM_CLEAR';
export const MEDICINE_WARNING_FORM_CHANGE_MODE = 'MEDICINE_WARNING_FORM_CHANGE_MODE';

export const MEDICINE_WARNING_CHANGE_LIST = 'MEDICINE_WARNING_CHANGE_LIST';
export const MEDICINE_WARNING_PUSH_LIST = 'MEDICINE_WARNING_PUSH_LIST';
export const MEDICINE_WARNING_REMOVE_LIST = 'MEDICINE_WARNING_REMOVE_LIST';
export const MEDICINE_WARNING_UPDATE_LIST = 'MEDICINE_WARNING_UPDATE_LIST';
export const MEDICINE_WARNING_CHANGE_SEARCH_LIST = 'MEDICINE_WARNING_CHANGE_SEARCH_LIST';
export const MEDICINE_WARNING_FILTER_LIST = 'MEDICINE_WARNING_FILTER_LIST';

export const MEDICINE_WARNING_CHANGE_DETAIL = 'MEDICINE_WARNING_CHANGE_DETAIL';