export const DOCTOR_FORM_CHANGE = 'DOCTOR_FORM_CHANGE';
export const DOCTOR_FORM_VALIDATION = 'DOCTOR_FORM_VALIDATION';
export const DOCTOR_FORM_CLEAR = 'DOCTOR_FORM_CLEAR';
export const DOCTOR_FORM_CHANGE_MODE = 'DOCTOR_FORM_CHANGE_MODE';

export const DOCTOR_CHANGE_LIST = 'DOCTOR_CHANGE_LIST';
export const DOCTOR_PUSH_LIST = 'DOCTOR_PUSH_LIST';
export const DOCTOR_REMOVE_LIST = 'DOCTOR_REMOVE_LIST';
export const DOCTOR_UPDATE_LIST = 'DOCTOR_UPDATE_LIST';
export const DOCTOR_CHANGE_SEARCH_LIST = 'DOCTOR_CHANGE_SEARCH_LIST';
export const DOCTOR_FILTER_LIST = 'DOCTOR_FILTER_LIST';

export const DOCTOR_CHANGE_DETAIL = 'DOCTOR_CHANGE_DETAIL';