//TẢI LIST INTERNAL STOCK DELIVERY
export const PRODUCT_INPUT_CHANGE_LIST = 'PRODUCT_INPUT_CHANGE_LIST';
export const PRODUCT_INPUT_CHANGE_LIST_CHILD = 'PRODUCT_INPUT_CHANGE_LIST_CHILD';
export const PRODUCT_INPUT_CLEAR_LIST_CHILD = 'PRODUCT_INPUT_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const PRODUCT_INPUT_PUSH_LIST_CHILD = 'PRODUCT_INPUT_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const PRODUCT_INPUT_CHANGE_SELECTED_DETAIL = 'PRODUCT_INPUT_CHANGE_SELECTED_DETAIL';
export const PRODUCT_INPUT_CLEAR_SELECTED_DETAIL = 'PRODUCT_INPUT_CLEAR_SELECTED_DETAIL';
export const PRODUCT_INPUT_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'PRODUCT_INPUT_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const PRODUCT_INPUT_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'PRODUCT_INPUT_CLEAR_LIST_CHILD_SELECTED_DETAIL';

export const PRODUCT_INPUT_FORM_CHANGE = 'PRODUCT_INPUT_FORM_CHANGE';
export const PRODUCT_INPUT_FORM_VALIDATION = 'PRODUCT_INPUT_FORM_VALIDATION';
export const PRODUCT_INPUT_FORM_CHANGE_VALUES = 'PRODUCT_INPUT_FORM_CHANGE_VALUES';
export const PRODUCT_INPUT_FORM_CLEAR = 'PRODUCT_INPUT_FORM_CLEAR'; //CLEAR FORM CHA
export const PRODUCT_INPUT_CHANGE_MODE = 'PRODUCT_INPUT_CHANGE_MODE';

export const PRODUCT_INPUT_FORM_CHILD_CHANGE = 'PRODUCT_INPUT_FORM_CHILD_CHANGE';
export const PRODUCT_INPUT_FORM_CHILD_CHANGE_MODE = 'PRODUCT_INPUT_FORM_CHILD_CHANGE_MODE';
export const PRODUCT_INPUT_FORM_CHILD_CLEAR = 'PRODUCT_INPUT_FORM_CHILD_CLEAR';
export const PRODUCT_INPUT_FORM_CHILD_VALIDATION = 'PRODUCT_INPUT_FORM_CHILD_VALIDATION';