export const UNIT_FORM_CHANGE = 'UNIT_FORM_CHANGE';
export const UNIT_FORM_VALIDATION = 'UNIT_FORM_VALIDATION';
export const UNIT_FORM_CLEAR = 'UNIT_FORM_CLEAR';
export const UNIT_FORM_CHANGE_MODE = 'UNIT_FORM_CHANGE_MODE';

export const UNIT_CHANGE_LIST = 'UNIT_CHANGE_LIST';
export const UNIT_PUSH_LIST = 'UNIT_PUSH_LIST';
export const UNIT_REMOVE_LIST = 'UNIT_REMOVE_LIST';
export const UNIT_UPDATE_LIST = 'UNIT_UPDATE_LIST';
export const UNIT_CHANGE_SEARCH_LIST = 'UNIT_CHANGE_SEARCH_LIST';
export const UNIT_FILTER_LIST = 'UNIT_FILTER_LIST';

export const UNIT_CHANGE_DETAIL = 'UNIT_CHANGE_DETAIL';