//TẢI LIST INTERNAL STOCK DELIVERY
export const WHOLE_SALER_CHANGE_LIST = 'WHOLE_SALER_CHANGE_LIST';
export const WHOLE_SALER_CHANGE_LIST_CHILD = 'WHOLE_SALER_CHANGE_LIST_CHILD';
export const WHOLE_SALER_CLEAR_LIST_CHILD = 'WHOLE_SALER_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const WHOLE_SALER_PUSH_LIST_CHILD = 'WHOLE_SALER_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const WHOLE_SALER_CHANGE_SELECTED_DETAIL = 'WHOLE_SALER_CHANGE_SELECTED_DETAIL';
export const WHOLE_SALER_CLEAR_SELECTED_DETAIL = 'WHOLE_SALER_CLEAR_SELECTED_DETAIL';
export const WHOLE_SALER_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'WHOLE_SALER_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const WHOLE_SALER_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'WHOLE_SALER_CLEAR_LIST_CHILD_SELECTED_DETAIL';

export const WHOLE_SALER_FORM_CHANGE = 'WHOLE_SALER_FORM_CHANGE';
export const WHOLE_SALER_FORM_VALIDATION = 'WHOLE_SALER_FORM_VALIDATION';
export const WHOLE_SALER_FORM_CHANGE_VALUES = 'WHOLE_SALER_FORM_CHANGE_VALUES';
export const WHOLE_SALER_FORM_CLEAR = 'WHOLE_SALER_FORM_CLEAR'; //CLEAR FORM CHA
export const WHOLE_SALER_CHANGE_MODE = 'WHOLE_SALER_CHANGE_MODE';

export const WHOLE_SALER_FORM_CHILD_CHANGE = 'WHOLE_SALER_FORM_CHILD_CHANGE';
export const WHOLE_SALER_FORM_CHILD_CHANGE_MODE = 'WHOLE_SALER_FORM_CHILD_CHANGE_MODE';
export const WHOLE_SALER_FORM_CHILD_CLEAR = 'WHOLE_SALER_FORM_CHILD_CLEAR';
export const WHOLE_SALER_FORM_CHILD_VALIDATION = 'WHOLE_SALER_FORM_CHILD_VALIDATION';