//TẢI LIST INTERNAL STOCK DELIVERY
export const THUOC_DANG_DUOC_BAN_CHANGE_LIST = 'THUOC_DANG_DUOC_BAN_CHANGE_LIST';
export const THUOC_DANG_DUOC_BAN_CHANGE_LIST_CHILD = 'THUOC_DANG_DUOC_BAN_CHANGE_LIST_CHILD';
export const THUOC_DANG_DUOC_BAN_CLEAR_LIST_CHILD = 'THUOC_DANG_DUOC_BAN_CLEAR_LIST_CHILD';
export const THUOC_DANG_DUOC_BAN_CLEAR_LIST = 'THUOC_DANG_DUOC_BAN_CLEAR_LIST';
//THÊM VÀO LIST CHILD
export const THUOC_DANG_DUOC_BAN_PUSH_LIST_CHILD = 'THUOC_DANG_DUOC_BAN_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const THUOC_DANG_DUOC_BAN_CHANGE_SELECTED_DETAIL = 'THUOC_DANG_DUOC_BAN_CHANGE_SELECTED_DETAIL';
export const THUOC_DANG_DUOC_BAN_CLEAR_SELECTED_DETAIL = 'THUOC_DANG_DUOC_BAN_CLEAR_SELECTED_DETAIL';
export const THUOC_DANG_DUOC_BAN_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'THUOC_DANG_DUOC_BAN_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const THUOC_DANG_DUOC_BAN_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'THUOC_DANG_DUOC_BAN_CLEAR_LIST_CHILD_SELECTED_DETAIL';
export const THUOC_DANG_DUOC_BAN_CHANGE_SEARCH_LIST = 'THUOC_DANG_DUOC_BAN_CHANGE_SEARCH_LIST';

export const THUOC_DANG_DUOC_BAN_FORM_CHANGE = 'THUOC_DANG_DUOC_BAN_FORM_CHANGE';
export const THUOC_DANG_DUOC_BAN_FORM_VALIDATION = 'THUOC_DANG_DUOC_BAN_FORM_VALIDATION';
export const THUOC_DANG_DUOC_BAN_FORM_CHANGE_VALUES = 'THUOC_DANG_DUOC_BAN_FORM_CHANGE_VALUES';
export const THUOC_DANG_DUOC_BAN_FORM_CLEAR = 'THUOC_DANG_DUOC_BAN_FORM_CLEAR'; //CLEAR FORM CHA
export const THUOC_DANG_DUOC_BAN_CHANGE_MODE = 'THUOC_DANG_DUOC_BAN_CHANGE_MODE';

export const THUOC_DANG_DUOC_BAN_FORM_CHILD_CHANGE = 'THUOC_DANG_DUOC_BAN_FORM_CHILD_CHANGE';
export const THUOC_DANG_DUOC_BAN_FORM_CHILD_CHANGE_MODE = 'THUOC_DANG_DUOC_BAN_FORM_CHILD_CHANGE_MODE';
export const THUOC_DANG_DUOC_BAN_FORM_CHILD_CLEAR = 'THUOC_DANG_DUOC_BAN_FORM_CHILD_CLEAR';
export const THUOC_DANG_DUOC_BAN_FORM_CHILD_VALIDATION = 'THUOC_DANG_DUOC_BAN_FORM_CHILD_VALIDATION';