export const CUSTOMER_GROUP_FORM_CHANGE = 'CUSTOMER_GROUP_FORM_CHANGE';
export const CUSTOMER_GROUP_FORM_VALIDATION = 'CUSTOMER_GROUP_FORM_VALIDATION';
export const CUSTOMER_GROUP_FORM_CLEAR = 'CUSTOMER_GROUP_FORM_CLEAR';
export const CUSTOMER_GROUP_FORM_CHANGE_MODE = 'CUSTOMER_GROUP_FORM_CHANGE_MODE';

export const CUSTOMER_GROUP_CHANGE_LIST = 'CUSTOMER_GROUP_CHANGE_LIST';
export const CUSTOMER_GROUP_PUSH_LIST = 'CUSTOMER_GROUP_PUSH_LIST';
export const CUSTOMER_GROUP_REMOVE_LIST = 'CUSTOMER_GROUP_REMOVE_LIST';
export const CUSTOMER_GROUP_UPDATE_LIST = 'CUSTOMER_GROUP_UPDATE_LIST';
export const CUSTOMER_GROUP_CHANGE_SEARCH_LIST = 'CUSTOMER_GROUP_CHANGE_SEARCH_LIST';
export const CUSTOMER_GROUP_FILTER_LIST = 'CUSTOMER_GROUP_FILTER_LIST';

export const CUSTOMER_GROUP_CHANGE_DETAIL = 'CUSTOMER_GROUP_CHANGE_DETAIL';