export const TREATMENT_GROUP_FORM_CHANGE = 'TREATMENT_GROUP_FORM_CHANGE';
export const TREATMENT_GROUP_FORM_VALIDATION = 'TREATMENT_GROUP_FORM_VALIDATION';
export const TREATMENT_GROUP_FORM_CLEAR = 'TREATMENT_GROUP_FORM_CLEAR';
export const TREATMENT_GROUP_FORM_CHANGE_MODE = 'TREATMENT_GROUP_FORM_CHANGE_MODE';

export const TREATMENT_GROUP_CHANGE_LIST = 'TREATMENT_GROUP_CHANGE_LIST';
export const TREATMENT_GROUP_PUSH_LIST = 'TREATMENT_GROUP_PUSH_LIST';
export const TREATMENT_GROUP_REMOVE_LIST = 'TREATMENT_GROUP_REMOVE_LIST';
export const TREATMENT_GROUP_UPDATE_LIST = 'TREATMENT_GROUP_UPDATE_LIST';
export const TREATMENT_GROUP_CHANGE_SEARCH_LIST = 'TREATMENT_GROUP_CHANGE_SEARCH_LIST';
export const TREATMENT_GROUP_FILTER_LIST = 'TREATMENT_GROUP_FILTER_LIST';

export const TREATMENT_GROUP_CHANGE_DETAIL = 'TREATMENT_GROUP_CHANGE_DETAIL';