//TẢI LIST INTERNAL STOCK DELIVERY
export const HOA_DON_NHAP_XUAT_CHANGE_LIST = 'HOA_DON_NHAP_XUAT_CHANGE_LIST';
export const HOA_DON_NHAP_XUAT_CHANGE_LIST_CHILD = 'HOA_DON_NHAP_XUAT_CHANGE_LIST_CHILD';
export const HOA_DON_NHAP_XUAT_CLEAR_LIST_CHILD = 'HOA_DON_NHAP_XUAT_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const HOA_DON_NHAP_XUAT_PUSH_LIST_CHILD = 'HOA_DON_NHAP_XUAT_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const HOA_DON_NHAP_XUAT_CHANGE_SELECTED_DETAIL = 'HOA_DON_NHAP_XUAT_CHANGE_SELECTED_DETAIL';
export const HOA_DON_NHAP_XUAT_CLEAR_SELECTED_DETAIL = 'HOA_DON_NHAP_XUAT_CLEAR_SELECTED_DETAIL';
export const HOA_DON_NHAP_XUAT_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'HOA_DON_NHAP_XUAT_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const HOA_DON_NHAP_XUAT_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'HOA_DON_NHAP_XUAT_CLEAR_LIST_CHILD_SELECTED_DETAIL';

export const HOA_DON_NHAP_XUAT_FORM_CHANGE = 'HOA_DON_NHAP_XUAT_FORM_CHANGE';
export const HOA_DON_NHAP_XUAT_FORM_VALIDATION = 'HOA_DON_NHAP_XUAT_FORM_VALIDATION';
export const HOA_DON_NHAP_XUAT_FORM_CHANGE_VALUES = 'HOA_DON_NHAP_XUAT_FORM_CHANGE_VALUES';
export const HOA_DON_NHAP_XUAT_FORM_CLEAR = 'HOA_DON_NHAP_XUAT_FORM_CLEAR'; //CLEAR FORM CHA
export const HOA_DON_NHAP_XUAT_CHANGE_MODE = 'HOA_DON_NHAP_XUAT_CHANGE_MODE';

export const HOA_DON_NHAP_XUAT_FORM_CHILD_CHANGE = 'HOA_DON_NHAP_XUAT_FORM_CHILD_CHANGE';
export const HOA_DON_NHAP_XUAT_FORM_CHILD_CHANGE_MODE = 'HOA_DON_NHAP_XUAT_FORM_CHILD_CHANGE_MODE';
export const HOA_DON_NHAP_XUAT_FORM_CHILD_CLEAR = 'HOA_DON_NHAP_XUAT_FORM_CHILD_CLEAR';
export const HOA_DON_NHAP_XUAT_FORM_CHILD_VALIDATION = 'HOA_DON_NHAP_XUAT_FORM_CHILD_VALIDATION';