//TẢI LIST INTERNAL STOCK DELIVERY
export const XUAT_HUY_HANG_CHANGE_LIST = 'XUAT_HUY_HANG_CHANGE_LIST';
export const XUAT_HUY_HANG_CHANGE_SEARCH_HOA_DON_LIST = 'XUAT_HUY_HANG_CHANGE_SEARCH_HOA_DON_LIST';
export const XUAT_HUY_HANG_CHANGE_LIST_CHILD = 'XUAT_HUY_HANG_CHANGE_LIST_CHILD';
export const XUAT_HUY_HANG_CLEAR_LIST_CHILD = 'XUAT_HUY_HANG_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const XUAT_HUY_HANG_PUSH_LIST_CHILD = 'XUAT_HUY_HANG_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const XUAT_HUY_HANG_CHANGE_SELECTED_DETAIL = 'XUAT_HUY_HANG_CHANGE_SELECTED_DETAIL';
export const XUAT_HUY_HANG_CLEAR_SELECTED_DETAIL = 'XUAT_HUY_HANG_CLEAR_SELECTED_DETAIL';
export const XUAT_HUY_HANG_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'XUAT_HUY_HANG_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const XUAT_HUY_HANG_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'XUAT_HUY_HANG_CLEAR_LIST_CHILD_SELECTED_DETAIL';
export const XUAT_HUY_HANG_CHANGE_SEARCH_LIST = 'XUAT_HUY_HANG_CHANGE_SEARCH_LIST';

export const XUAT_HUY_HANG_FORM_CHANGE = 'XUAT_HUY_HANG_FORM_CHANGE';
export const XUAT_HUY_HANG_FORM_VALIDATION = 'XUAT_HUY_HANG_FORM_VALIDATION';
export const XUAT_HUY_HANG_FORM_CHANGE_VALUES = 'XUAT_HUY_HANG_FORM_CHANGE_VALUES';
export const XUAT_HUY_HANG_FORM_CLEAR = 'XUAT_HUY_HANG_FORM_CLEAR'; //CLEAR FORM CHA
export const XUAT_HUY_HANG_CHANGE_MODE = 'XUAT_HUY_HANG_CHANGE_MODE';

export const XUAT_HUY_HANG_FORM_CHILD_CHANGE = 'XUAT_HUY_HANG_FORM_CHILD_CHANGE';
export const XUAT_HUY_HANG_FORM_CHILD_CHANGE_MODE = 'XUAT_HUY_HANG_FORM_CHILD_CHANGE_MODE';
export const XUAT_HUY_HANG_FORM_CHILD_CLEAR = 'XUAT_HUY_HANG_FORM_CHILD_CLEAR';
export const XUAT_HUY_HANG_FORM_CHILD_VALIDATION = 'XUAT_HUY_HANG_FORM_CHILD_VALIDATION';