//TẢI LIST INTERNAL STOCK DELIVERY
export const NHAP_HANG_TON_DAU_CHANGE_LIST = 'NHAP_HANG_TON_DAU_CHANGE_LIST';
export const NHAP_HANG_TON_DAU_CHANGE_LIST_CHILD = 'NHAP_HANG_TON_DAU_CHANGE_LIST_CHILD';
export const NHAP_HANG_TON_DAU_CLEAR_LIST_CHILD = 'NHAP_HANG_TON_DAU_CLEAR_LIST_CHILD';
//THÊM VÀO LIST CHILD
export const NHAP_HANG_TON_DAU_PUSH_LIST_CHILD = 'NHAP_HANG_TON_DAU_PUSH_LIST_CHILD';

//CHỌN DETAIL CHO INTERNAL STOCK DELIVERY
export const NHAP_HANG_TON_DAU_CHANGE_SELECTED_DETAIL = 'NHAP_HANG_TON_DAU_CHANGE_SELECTED_DETAIL';
export const NHAP_HANG_TON_DAU_CLEAR_SELECTED_DETAIL = 'NHAP_HANG_TON_DAU_CLEAR_SELECTED_DETAIL';
export const NHAP_HANG_TON_DAU_CHANGE_LIST_CHILD_SELECTED_DETAIL = 'NHAP_HANG_TON_DAU_CHANGE_LIST_CHILD_SELECTED_DETAIL';
export const NHAP_HANG_TON_DAU_CLEAR_LIST_CHILD_SELECTED_DETAIL = 'NHAP_HANG_TON_DAU_CLEAR_LIST_CHILD_SELECTED_DETAIL';

export const NHAP_HANG_TON_DAU_FORM_CHANGE = 'NHAP_HANG_TON_DAU_FORM_CHANGE';
export const NHAP_HANG_TON_DAU_FORM_VALIDATION = 'NHAP_HANG_TON_DAU_FORM_VALIDATION';
export const NHAP_HANG_TON_DAU_FORM_CHANGE_VALUES = 'NHAP_HANG_TON_DAU_FORM_CHANGE_VALUES';
export const NHAP_HANG_TON_DAU_FORM_CLEAR = 'NHAP_HANG_TON_DAU_FORM_CLEAR'; //CLEAR FORM CHA
export const NHAP_HANG_TON_DAU_CHANGE_MODE = 'NHAP_HANG_TON_DAU_CHANGE_MODE';

export const NHAP_HANG_TON_DAU_FORM_CHILD_CHANGE = 'NHAP_HANG_TON_DAU_FORM_CHILD_CHANGE';
export const NHAP_HANG_TON_DAU_FORM_CHILD_CHANGE_MODE = 'NHAP_HANG_TON_DAU_FORM_CHILD_CHANGE_MODE';
export const NHAP_HANG_TON_DAU_FORM_CHILD_CLEAR = 'NHAP_HANG_TON_DAU_FORM_CHILD_CLEAR';
export const NHAP_HANG_TON_DAU_FORM_CHILD_VALIDATION = 'NHAP_HANG_TON_DAU_FORM_CHILD_VALIDATION';